data/an4.py

Fixed an4 dataloading

---

decoder.py

I am running this with python 3.  Its working now.

Use six.moves for xrange in python3

---

train.py

Fix dropout when model is not training.

test in eval mode

---

README.md
data/an4.py
data/data_loader.py
data/ted.py
data/voxforge.py
requirements.txt

Hello,
I have created a simple script that downloads and parses TEDLIUM v2 dataset from http://www.openslr.org/resources/19/TEDLIUM_release2.tar.gz and creates train/val/test manifests.

added samples TED and VoxForge datasets

---

model.py
train.py

I have added an option to select which type of the rnn to use in the DeepSpeech module - Simple RNN, GRU or LSTM. What do you think of it @SeanNaren ? With batch norm simple rnn shows suprisingly good performance and faster to train.

added support of simple_rnn, gru and lstm for the deepspeech module

---

train.py

Fixed epoch count

---

README.md
data/librispeech.py
data/ted.py
data/utils.py
data/voxforge.py

Added support of LibriSpeech loader #24.
By default downloads all the files. This behaviour can be adjusted through the --files_to_dl flag, which accepts list of file names to download.

LibriSpeech dataset

---

README.md
data/data_loader.py
noise_inject.py

Added noise injection script

---

logger.py
train.py

As mentioned in #79, this pull request adds tensorboard logging as an option and also fixes some bugs in using visdom from a checkpointed model.

Added tensorboard logging

---

train.py

Typo in train.py variable definition.

Fix typo in train.py

---

README.md
benchmark.py
model.py
test.py

Updated the README with inference/eval stuff, and fixed var names in the test script

Updated Test variable and README information

---

benchmark.py
logger.py
model.py
train.py

Added parameter size count, various refactor of main training class

---

train.py

Minor fix, wer/cer/avg_loss are stored only when tensorboard or visdom flags are set

save wer/cer and avg_loss during training

---

data/data_loader.py

Removed encoding since it happens internally

---

data/bucketing_sampler.py

fixes error after first epoch when switching to bucketing sampler

fixed super() initialization error

---

data/data_loader.py
train.py

If one would continue from the checkpoint the sampler would be the sequential one and this PR fixes it.

Use bucketing sampler while continue_from

---

README.md

Added features list

---

data/data_loader.py

Addresses #119 
Not extensively tested though. It doesn't break any code.

add sample rate to data augmentation

---

train.py

change the action of "no_bucketing" argument to "store_true"

fix bug in turning off bucketing sampler

---

model.py

Fixes #139 
I've done some measurements on time spent doing this per forward, and the difference is negligible.

Added flatten params

---

data/data_loader.py

- remove complex circular calculation
- using sox, load only the noise segment needed from huge noise files
- considered the signal and the noise power in combining

modify noise injection routine

---

README.md
decoder.py
test.py
train.py
transcribe.py

Closes #136 and any offset based stuff!

Fixed merged repeated, added offsets

---

model.py

This PR fixes three issues:
1. squelches _some_ of the `flatten_parameters` warnings when on multi-gpu machines. There may still be an additional fix required (perhaps a call after the `DataParallel` call?).
2. Adds padding to the first CNN. It appears that utterances that start at the very beginning of an audio file are currently not well-handled due to the edge-effects. This has the added effect of further simplifying the time-alignment math.
3. Adds a "blacklist" of parameters to not load. This makes it possible to easily load older DeepSpeech models which had an architecture that included an unused BatchNorm on the first RNN.

Fix minor model issues

---

train.py

Added the ability to finetune a model from a checkpoint path instead of continuing to train from the checkpoint.

Added Fine-tuning enhancement

---

model.py
train.py

Fix continue training

---

README.md
decoder.py
generate_lm_dict.py
model.py
test.py
transcribe.py

Update to the most recent beamsearch decoder: https://github.com/parlance/ctcdecode.

Decoder update

---

README.md
model.py
train.py

Allows adding a Lookahead layer in unidirectional rnns
Thanks

Lookahead layer

---

README.md
decoder.py
test.py
transcribe.py
tune_decoder.py

Changed all `trie_path` to `dict_path` as it can get confusing if you have trie compressed lm files named with the `trie` extension!

Changed trie path to dict path for readability

---

transcribe.py

Due to changes in the decoder, the word decode function hasn't been correctly updated (since the functionality is missing). Will update the master repo to modify the output of the transcribe function and will create new tickets to re-implement this.

Replaced word_decode with json only due to decoder changes

---

train.py

Added manual seeds to training script

---

data/an4.py
data/librispeech.py
data/merge_manifests.py
data/ted.py
data/utils.py
data/voxforge.py

Split librispeech test, added pruning to all training/refactors.

Data fixes

---

data/common_voice.py

Add script to process MOZILLA COMMON VOICE DATASET.

MOZILLA COMMON VOICE DATASET

---

transcribe.py

Remove python 3 idiom in transcribe.py and replace with something backward-compatible

Fix Python3 only idiom in transcribe.py

---

tune_decoder.py

Useful info that I wish was there in the print logs of `tune_decoder.py`

Indices in the print logs

---

test.py

The current WER and CER calculations return average WER/CER across utterances which ends up over-emphasizing errors on short utterances and under-emphasizing good performance on long utterances. This addresses the issue and returns WER/CER more directly comparable with other frameworks.

Fix WER & CER calculations

---

Dockerfile
README.md

Related to issue #248
This is a first proposal which install deepspeech2 and launch a notebook to use it.

First version of a deepspeech2.pytorch docker

---

Dockerfile

Updating env varible to ensure CTC lib is known. I can't make it work properly without it on AWS.

Simple update on Dockerfile

---

data/data_loader.py
model.py
test.py
train.py
transcribe.py
tune_decoder.py

This PR contains a few improvement/refactors:
- Integrate variable lengths into the model
- Handle bug where at inference time batch size causes different output results from the model
- Fixed conv layer parameters
- Clean various compatibility code as well as use 3.5+ python os.makedirs function calls
This PR will make previous release models incompatible with the master branch, thus must use previous commit hashes given with the release to run them.

Various improvements

---

README.md
data/utils.py
multiproc.py
train.py

Fixes #322 as well as sync losses across training processes

Add GPU IDs for multiproc script, sync losses

---

Dockerfile
README.md
benchmark.py
data/common_voice.py
logger.py
model.py
multiproc.py
server.py
test.py
train.py
transcribe.py
tune_decoder.py
utils.py

Bunch of fixes within this PR:
- Simplified code where possible, primarily in logging, model load/save
- Simplified Dockerfile
- Added mixed precision support for volta cards
- Better checking of warp-ctc loss output to prevent grad explosions (soon to be replaced by built in loss once PyTorch 1.01 comes out)
- README changes
Haven't thoroughly tested this yet, will ensure everything works as expected

Major refactors

---

transcribe.py

Calling static method get_meta which was removed in the last commit.

removed call to removed static methods

---

model.py

Fixed saving mixed-precision based models

---

train.py

Fixed issue where continue_from option unconditionally overwrites best_wer.

Fixed the best_wer problem in continue_from option.

---

Dockerfile

Updated PyTorch/CUDNN version to fix warp-ctc

---

model.py

Currently, the lookahead implementation increases the memory required to train models. In my case, I had to use a batch size of 16 instead of 32 to avoid memory issues. 
This PR fixes the memory issues by performing the row convolutional operation (lookahead) with pytorch's Conv1D layer. 
I'm currently running tests to see whether it is beneficial to also include batch normalization and/or bias to the lookahead layer with a private dataset. Will update this PR if that is the case. 
Please tell me if you spot something being off with the improvement.
Fixes #274

Make lookahead rely on native pytorch Conv1d

---

test.py
train.py

Use the same evaluation function in training/testing, ensure that we remove space characters before computing CER
Should fix #420 and https://github.com/SeanNaren/deepspeech.pytorch/issues/446#issuecomment-517429594

Evaluation fixes

---

test.py

I think it should be 'Batch size for testing' not 'Batch size for training' in test.py.

minor option description change.

---

model.py
train.py

- Clip correct gradients, when using mixed precision
- Add amp state to model checkpoints, load amp state from checkpoint

Fix gradient clipping amp compatibility, save and load amp state

---

README.md
data/data_loader.py
data/sparse_image_warp.py
data/spec_augment.py
train.py

Adapted the SpecAugment implementation from [here](https://github.com/DemisEom/SpecAugment) for this project. Made a few modifications for integration with DeepSpeech2.
This PR also fixes #409 I believe.

SpecAugment Implementation

---

translations/README_JP.md

I translated README into Japanese.

Added Japanese language translated README

---

decoder.py
train.py

Modified labels into a list based on upstream ctcdecode changes

---

requirements.txt

When i pull the docker image and try to execute the different codes, i face some errors that i pass over by pip installing flask and matplotlib in the conatiner.

Needed for docker container.

---

README.md

Updating Tensorboard Command, including a '-'  in between log-dir.

Updating Tensorboard Command

---

train.py

#505 
Far more stable than SGD, will probably use for the next release and replace SGD as default.

Added AdamW optimizer

---

data/an4.py
requirements.txt

Pretty explanatory, I was lazy with this since AN4 was a really really small dataset and it's results are useful in very little situations...
Now AN4 has a validation set created from its training samples, and the test set is left out of the training process as it should be.

Modify AN4 preprocessing script to extract a validation set created from the training set

---

.gitignore
data/data_loader.py
requirements.txt

Resolves https://github.com/SeanNaren/deepspeech.pytorch/issues/495

Using soundfile.read to include more than just .wav files

---

README.md
config.yaml
requirements.txt
train.py

Closes #540 
Should make configuration a bit simpler and removes the unwieldy opts in the train.py file. Still tried to keep verbosity via the comments.

Hydra Integration

---

data/an4.py
data/common_voice.py
data/librispeech.py
data/ted.py
data/voxforge.py
deepspeech_pytorch/data/data_opts.py
deepspeech_pytorch/data/utils.py

Updated processing scripts to use common functions saved in the package, allow manifest directory to be changed

Improve data scripts

---

requirements.txt

https://github.com/deezer/spleeter/issues/419#issuecomment-643515960

Added Docker fix for Librosa due to deprecation

---

kubernetes/README.md
kubernetes/data/persistent_volume.yaml
kubernetes/data/storage.yaml
kubernetes/data/transfer_data.yaml
kubernetes/train.yaml

Added scripts and a tutorial on how to use deepspeech.pytorch using a GKE cluster.
Very useful for training on preemptive nodes whilst handling interruptions!

deepspeech.pytorch TorchElastic K8s support

---

search_lm_params.py

Added parameters --lm-path, --lm-workers, --beam-width to the parser.
Removed stale import and call to it which was used to add above parameters previously.

Fixes #570

---

deepspeech_pytorch/configs/inference_config.py

Fix arg type causing LM decoder crash

---

deepspeech_pytorch/model.py

Similar to #601, specify the blank index to the CTC Loss explicitly.

Add blank index to ctc loss explicitly

---

deepspeech_pytorch/training.py

Use correct class

---

README.md
data/merge_manifests.py

It looks like the merge manifests script was deleted.
Adding it here once more with slightly different usage.
I use symlinks to minimize disk space usage.

Merge Manifests Script

---

data/verify_manifest.py

Add a script that verifies all files in the manifest exist.

Verify manifests script

---

.github/workflows/test.yaml
configs/an4.yaml
configs/commonvoice.yaml
configs/librispeech.yaml
configs/tedlium.yaml
deepspeech_pytorch/checkpoint.py
deepspeech_pytorch/configs/lightning_config.py
deepspeech_pytorch/configs/train_config.py
deepspeech_pytorch/training.py
deepspeech_pytorch/validation.py
requirements.txt
test.py
train.py
transcribe.py

Closes #662 
Fixes deprecations in Lightning and changes in Hydra.
The fixes are not the cleanest, however I think currently is necessary. I'm leaning towards removing Hydra completely in the next release, as structured conf support has been painful. I think long term, relying on the LightningCLI which was lucky to be added as a dependency within Lightning means that the support for it should remain handling all these deprecations (I know a full time engineer is pretty much always available for LightningCLI).

Lots of fixes due to deprecations in lightning and changes in hydra

---

Dockerfile
configs/an4.yaml
configs/commonvoice.yaml
configs/librispeech.yaml
configs/tedlium.yaml
data/an4.py
deepspeech_pytorch/configs/lightning_config.py
deepspeech_pytorch/configs/train_config.py
deepspeech_pytorch/loader/data_module.py
deepspeech_pytorch/training.py
requirements.txt
tests/smoke_test.py

Fix the AN4 download since the dataset seems to have disappeared off the face of the planet... If someone has the original an4 download tar file, I'd appreciate it!
closes #679  
closes #670 
closes #677

Fix an4 download, and dockerfile

---

.gitignore
README.md
deepspeech_pytorch/configs/inference_config.py
deepspeech_pytorch/inference.py
deepspeech_pytorch/loader/data_loader.py
deepspeech_pytorch/model.py
deepspeech_pytorch/validation.py

Hi @SeanNaren,
This pull request contains the needed modifications to support transcribing long audio files that do not fit in the GPU. I made use of the auto-regression property of RNNs to feed the last hidden states of every audio chunk after processing to the next chunk as an input to preserve the flow of the sequence information between audio chunks. I've tested the code on an audio file of length more than 1 hour and it worked!

Support Transcribing Long Audio Files
