SeanNaren/deepspeech.pytorch

train.py
Running a dataset besides an4 I hit this, and got NoneType errors since params with no gradients arent filtered.  The pytorch utility torch.nn.utils.clip_grad_norm does this filtering internally, and once I replaced the clipping code with it, the exception went away
=> Using pytorch builtin avoids no-grad params

model.py, predict.py, test.py, train.py
When you train with a non-LSTM model, the test and predict scripts cannot properly load the model because the RNN type is not saved as metadata. Other miscellaneous fixes included (largely related to command-line arguments).
=> Fix model saving for different RNN types

README.md, model.py, predict.py, test.py, train.py
This merge request reworks the model saving/loading/checkpoint code. There are some breaking API changes here, so it's worth looking over carefully to ensure that they're all desirable changes.
At a high level, the checkpointing works the same way: we create a dict of the various metadata and extract the `state_dict`. This dict is then written with `torch.save`. What's different is that all of the model hyperparemeters are stored within the `DeepSpeech` model module. This simplifies some of the arguments that need passing during training and model loading.
To make the models GPU/CPU agnostic, the serialization code checks to see if the model is currently in CUDA mode. We assume that whenever this happens, `DataParallel` has also been used (which is a safe assumption considering how the …
=> Refactor model serialization & deserialization for CPU/GPU portability

README.md, data/data_loader.py, requirements.txt, train.py
Doing testing now using noise injection
=> Noise inject #35

train.py
The data loader checks if `noise_dir is None` and, if so, skips adding noise. Otherwise, it looks in the directory and tries to pull a random file. When the path to noise is invalid (ie ''), the script will crash.
=> Fix noise arg default in train script

model.py
Previously, the model.py script would return the minimum error/loss
that occurred during training. This isn't particularly informative
as it's possible that the minimum validation error/loss does not
correspond with the loss of the persisted model. This update prints
the loss/error for the saved model.
=> Return the current validation error/loss

data/merge_manifests.py
At the moment merge_manifests.py allows to set  min/max duration only jointly. This PR adds functionality to filter utterances by min/max individually.
=> Filtering by minimum and maximum duration individually

train.py
With the new model serialization format, models are saved as the CPU version always, so the `DataParallel()`/`cuda()` calls must always *follow* the `load_state_dict` calls. I introduced this error with the model serialization refactor. Sorry about that -- had this PR ready to go and then live intervened.
=> Fix train continue bug on cuda models

benchmark.py, predict.py, test.py, train.py
This PR reduces the memory footprint (mostly during inference) by eliminating portions of the autograd graph. I'm trying to track down any possible way we might reduce the overall memory footprint (esp. during training) to allow larger batch sizes. This was the first inefficiency I found.
What's interesting is:
1) I didn't notice much change in memory utilization during training/benchmark.
2) I noticed a SIGNIFICANT drop in memory usage during test.py, but no real speedup from dramatically increasing the batch size (though there was no OOM).
=> Manually set autograd params for reduced memory

data/bucketing_sampler.py, data/merge_manifests.py, data/utils.py, train.py
I think it might be a solution to #30. Instead of random sampling, we could split firstly the whole dataset into several buckets depending on the length of the utterance and then randomly sample from each of the buckets. As a result, we can have batches with similar length utterances.
=> Sampler that splits utterances into buckets

README.md, decoder.py, generate_lm_trie.py, model.py, predict.py, test.py, train.py
This is a WIP integration of beam search based on my port of the ctc beam decoder in tensorflow. Will address #86. 
Remaining:
If you want to test it out, you will need to manually install my pytorch_ctc bindings: https://github.com/ryanleary/pytorch-ctc
=> Add beam search

model.py
Rename the `softmax` into `inference_log_softmax` to emphasize that the output is linear in training time.
Concerns #121.
=> Refactor model output to reflect its type

decoder.py, model.py, test.py, transcribe.py, tune_decoder.py
`transcribe.py` is modified to take a `--word_json` parameter which returns a json-formatted transcription that includes the top path string, as well as all requested paths tokenized with word start/stop times and confidences (currently broken).
`test.py` is modified to optionally be able to skip decoding and simply write the logits to disk.
`tune_decoder.py` reads the written logits in and in parallel sweeps the alpha and beta parameters so that an optimal value may be chosen.
=> Add LM tuning functionality & detailed transcription output

README.md, benchmark.py, data/an4.py, data/common_voice.py, data/librispeech.py, data/merge_manifests.py, data/ted.py, data/voxforge.py, model.py, noise_inject.py, test.py, train.py, transcribe.py, tune_decoder.py
This may be a PITA for users who have written scripts around the various scripts here, but the current command-line arguments are non-standard in that they don't conform to POSIX standards. See https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html. This PR just replaces underscores with hyphens in all of the command line args (and associated docs!).
=> Switch cmd-line args to POSIX-style

README.md, model.py, test.py, train.py, transcribe.py, tune_decoder.py
Changing misleading file extensions in the testing and inference examples. These examples do not need `.tar` examples to work.
=> Fix misleading file extension in Testing/Inference example

decoder.py, test.py, train.py
Pass the sequence length of utterances within a batch to the underlying beam ctc decoder. Note: this requires the latest ctcdecode.
=> Pass sequence length to decoder

tune_decoder.py
1.  The outputs from decoder.decode are not correctly assigned. Some must have confused `BeamCTCDecoder.decode` with `CTCBeamDecoder.decode`
2. [This](https://github.com/SeanNaren/deepspeech.pytorch/commit/e1aef159148c5aa601a3811a2ab3fa5efe94ce5b) commit removed unnecessary transposes, because of which `batch_size` calculation messed up.
=> Fix tune decoder

README.md, benchmark.py, data/data_loader.py, data/distributed.py, multiproc.py, train.py
See #211 for more information!
=> Added multi-gpu support via distributed wrapper

data/voxforge.py
Hi
As mentioned [here](https://github.com/SeanNaren/deepspeech.pytorch/issues/257) I want dataset downloaders to act more rational, so I add a simple checking and avoid downloading processed files. The same pr will come for LibriSpeech asap.
The other change is removing unnecessary slash added to VOXFORGE_URL_16kHz, which makeu url looks something like this 
> http://www.repository.voxforge1.org/downloads/SpeechCorpus/Trunk/Audio/Main/16kHz_16bit//filename.tgz
=> avoid reprocessing cached files

data/data_loader.py
By default torchaudio loads unnormalized waveform. Maybe it makes sense to normalize within a range of 0-1 as torchaudio has a normalization parameter, which is turned off by default?
=> Normalizing audio within a 0-1 range

logger.py
Hi
In `train.py` at line 310-312, we write evaluation results at `epoch`'th index of `loss_results`, `wer_results` and `cer_results` tensors. While in `logger.py` we read violate variables from one ahead index (lines 21-23 in visdom logger and lines 46-47 in tensorboards logger). This cause to see nonsense log like this:
=> fix logger bug

train.py, utils.py
=> Added check to model to ensure we take off the distributed wrapper

search_lm_params.py, test.py
Hi
I tried to dump acoustic model output to search for optimum beam search parameters:
`python3.8 test.py --test-manifest /media/aj/vf/voxforge.csv --model-path models/deepspeech_final.pth --cuda --half --save-output voxforge.npy`
And I get the following error:
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:05<00:00,  1.16it/s]
Test Summary 	Average WER 51.965	Average CER 15.761	
Traceback (most recent call last):
File "test.py", line 101, in <module>
np.save(args.save_output, output_data)
File "<__array_function__ internals>", line 5, in save
File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 551, in save
arr = …
=> save output for lm search

multiproc.py, test.py
the first bug is in  `test.py`
the default value of the parameter `save_output` of the function `evaluate` is preferably `None`
because  the value of the conditional statements`save_output is not None`  is always `true` when `save_output= False`
----
the second bug is in `multiproc.py`
EASE:
```
python -m multiproc train.py --train-manifest data/train_manifest.csv --val-manifest data/val_manifest.csv --cuda --device-ids 1,2,3,
5
['train.py', '--train-manifest', 'data/train_manifest.csv', '--val-manifest', 'data/val_manifest.csv', '--cuda', '--world-size',
'4', '--rank', '0', '--gpu-rank', '0']
['train.py', '--train-manifest', 'data/train_manifest.csv', '--val-manifest', 'data/val_manifest.csv', '--cuda',  '--world-size',
'4', '--rank', '1', '--gpu-rank', '2']
['train.py', …
```
=> Fix two small bugs

data/sparse_image_warp.py
Fixed the warning probably below.
```
alpha = torch.tensor(queries - floor, dtype=grid_type)
./data/sparse_image_warp.py:375: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
```
=> Fix warnings of alpha = torch.tensor(queries - floor, dtype=grid_type)

deepspeech_pytorch/state.py
Hi
Loss values, CER and WER measures are stored in a `torch.IntTensor` instance, causing the error in visualization:
For e.g., the image above must depict a smooth reduction in CER measure (10.815, 10.434, 10.393, 10.384, 10.195, 9.974), but due to rounding the values to integers, it's plotted in a wrong fashion.
Regards
=> avoid perf measure rounding

README.md
changed the decoder arguments from double hyphen (--) to lm.args. The transcribe.py no longer accepts double hyphen parameters.
```
transcribe.py: error: unrecognized arguments: --decoder beam
```
=> fixed the readme for alternate decoders

deepspeech_pytorch/model.py
Hi
There is an error at `get_seq_len` method due to dividing `torch.LongTensor` by `/` operator:
`RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.`
Here is a fix for it.
=> bug fix for integer division

select_lm_params.py
Hi sean
I think it would be helpful to plot `wer` beside selecting the best decoder parameters. It will give a good vision to select searching parameter ranges more wisely. Here is a sample simple example:
best regards.
=> visualize wer

README.md
Hi,
In Multi-GPU Training using Docker, audio augmentation is done with `sox` and the output is written in `/tmp` by [NamedTemporaryFile](https://github.com/SeanNaren/deepspeech.pytorch/blob/a5e05de65275f5ea14123bb215e36ca3f5179a80/deepspeech_pytorch/loader/data_loader.py#L326). This mechanism utilizes the disk storage with a write and a read on container’s writable layer for each audio augmentation, if `/tmp` is not mounted with tmpfs:
While using Docker, it can be done by adding `--tmpfs /tmp` when creating a container:
```
$ docker run \
--interactive \
--tty \
--detach \
--name deepspeech-pytorch \
--gpus all \
--ipc=host \
--volume `pwd`/data:/workspace/data \
--entrypoint=/bin/bash \
--tmpfs /tmp \
seannaren/deepspeech.pytorch:latest
```
The created container has tmpfs mount for …
=> use tmpfs mount for /tmp in Docker

deepspeech_pytorch/utils.py
The `BeamCTCDecoder` assumes that the `blank_index` is always at position 0.
Specify it explicitly to avoid potential issues with labels.
Resolves #595
=> Specify blank index explicitly

deepspeech_pytorch/inference.py, deepspeech_pytorch/model.py, deepspeech_pytorch/validation.py
Resolve the warning
```
SyntaxWarning: "is" with a literal. Did you mean "=="?
with autocast(enabled=self.precision is 16):
```
=> Fix Syntax Warning

deepspeech_pytorch/loader/data_loader.py, requirements.txt
Use torchaudio instead of soundfile.
This allows us to use non-wave files like MP3.
`load()` already normalizes the data by default and returns a [channel x length] array.
Plus it has support for different codecs unsupported by `libsndfile`.
=> Use torchaudio

deepspeech_pytorch/data/utils.py
With the PyTorch lightning + torchaudio changes, we can now use non-wav files as well (like mp3).
The `create_manifest` utility however only looks for `*.wav` files.
Add an argument that allows us to change the extension we look for.
Also, print the total duration of the audio processed (might as well put it to some more use I guess...)
=> Print total duration and use non-wav file extensions

deepspeech_pytorch/configs/train_config.py, deepspeech_pytorch/training.py
if `trainer.callbacks` is not `[]` or specified in the yaml config, `training.py` will fail.
I don't see `trainer.callbacks` used anywhere and it seems it's already set manually later on so I removed it.
Also to support Hydra's nested instantation, I modified the checkpoint config field to be a base  `ModelCheckpointConf`
=> Fix GCS config

deepspeech_pytorch/checkpoint.py, deepspeech_pytorch/configs/train_config.py
I discovered another bug with the GCS config.
It looks like the `local_save_file` isn't really necessary since PTL trainer already saves the model locally.
Also, `GCSCheckpointHandler` complains (after completing an epoch, which is not ideal) that it can't find a saved file if it's not specified correctly.
We can instead upload the file that the trainer is already using and avoid having the user to manually specify a save file.
The `GCSCheckpointHandler` now also properly saves to the user's desired folder instead of the full path to the model
So previously it would be saved as some thing like `<bucket_name>/home/user/path/to/model.ckpt`
Now it actually saves it to the bucket/folder correctly.
=> Fix gcs config path

README.md
Release [V3.0](https://github.com/SeanNaren/deepspeech.pytorch/releases/tag/V3.0) has dropped CSV manifest files for training/testing in favor of JSON files. Unfortunately, the documentation hasn't since been updated leading to issues like #639.
As I was evaluating the pre-trained V3.0 models on a custom dataset, I personally reverse engineered [verify_manifest.py](https://github.com/SeanNaren/deepspeech.pytorch/blob/master/data/verify_manifest.py) to derive the new expected JSON data format. I have updated the README to demonstrate this new data format and to give a warning that CSV-friendliness was dropped after [V2.1](https://github.com/SeanNaren/deepspeech.pytorch/releases/tag/V2.1)
=> Documentation: Updated info on V3 manifest file format (CSV to JSON switch)

deepspeech_pytorch/configs/lightning_config.py, deepspeech_pytorch/configs/train_config.py, requirements.txt
Hi, @SeanNaren - Hope you're doing well. Lightning Ecosystem CI was failing with the following errors for a few attributes:
```bash
TypeError: __init__() got an unexpected keyword argument 'process_position'
```
These are some attributes that were removed in PL 1.7.0 release, post deprecation. This PR adds an alternative of each one of them, most of them as callbacks. `prepare_data_per_node` was shifted to `LightningDataModule/LightningModule` from `Trainer` in PL 1.7, so I've added it to the data configuration.
Note: post this PR, it's expected that the users will use latest PL release (>= 1.7.0) 🎉 
cc: @SeanNaren (also cc-ing: @Borda @carmocca for visibility) :)
=> Update: PL latest release

deepspeech_pytorch/loader/sparse_image_warp.py
Hi,
`deepspeech_pytorch/loader/sparse_image_warp.py` was using `torch.solve()`, which has been deprecated since PyTorch v1.9. I changed it to `torch.linalg.solve()`.
=> Replace deprecated function
